[phases.setup]
nixPkgs = ["php84", "php84-extensions", "composer", "nodejs"]

[phases.build]
cmds = [
    "php84 $(which composer) install --no-dev --optimize-autoloader --no-interaction",
    "npm install && npm run build"
]